import Head from 'next/head'
import styles from '../styles/HouseCarousel.module.css'
import FilterIcons from "../comps/FilterIcons"
import Link from "next/link"
import jsonData from "../data.json"

// pages/index.js
import Carousel from 'react-material-ui-carousel'
import { Paper } from '@mui/material'
import React from 'react'
import Registration from '../comps/Registration'
import { myContext } from './_app'
import FilterPopUp from '../comps/FilterPopUp'



export default function Home({initialData}) {
  const context = React.useContext(myContext)
/////////////////////////////////
  const [mainData, setMainData] = React.useState(initialData.srcs)

  const favouriteFunc = house => {
    const newData = mainData.map((item) => {
      if (item == house) {
        item.favourite = !item.favourite
        return item
      } else return item
    })
    setMainData(newData)
    context.setFavouriteHouses(mainData.filter(filteredItem => {
      return filteredItem.favourite
    }))
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <FilterIcons/>


        <div className={styles.carouselsContainer}>
          {mainData.map((item, index) => (
            <div className={styles.carouselContainer} key={index}>
              <span className={styles.carouselContainerLoveIcon}
                    style={{opacity: item.favourite? 1 : .5}}
                    onClick={() => favouriteFunc(item)}>
              </span>
          <Carousel key={item.id}
              autoPlay={false}
              navButtonsProps={{
                style: {
                  backgroundColor: '#458DB7',
                  padding: "3px"
                }
              }} 
              indicatorIconButtonProps={{
                style: {
                  color: '#999',
                  zIndex: 10,
                  marginBottom: "10px"
                                      }
                                    }}
                                    activeIndicatorIconButtonProps={{
                                      style: {
                                        color: '#458DB7',
                                        zIndex: 10 // 2
                                      }
                                  }}
                                  indicatorContainerProps={{
                                      style: {
                                          zIndex: 10,
                                          marginTop: "-20px",
                                      }
                                    }}
                                    >
            {item.images.map(img => <Item src={`/${img}`} height={30} width={30} id={item.id} key={item.id}/>)}
          </Carousel>

          </div>
))}

        
        </div>


      </main>
        {context.signUpCompShowed && <Registration />}


        <div>
          {context.filterClicked && <FilterPopUp mainData={mainData} setMainData={setMainData}/>}
        </div>
    </div>
  )
}

// Fetching data from the JSON file

Home.getInitialProps = async () => {
  return {initialData: jsonData}
}

function Item(props)
{

    return (
        <Link href={`/houses/${props.id}`}>
          <Paper className={styles.innerCarousel} style={{background: `url(${props.src}) center no-repeat`
                ,backgroundSize: "cover" ,height: "190px", borderRadius: "15px"}}>
          </Paper>
        </Link>
    )
}
